CREATE DATABASE IF NOT EXISTS STUDENT_MANAGEMENT_SYSTEM;
USE STUDENT_MANAGEMENT_SYSTEM;
CREATE TABLE DEPARTMENT(
DEPT_ID INT PRIMARY KEY AUTO_INCREMENT,
DEPT_NAME VARCHAR(100) UNIQUE NOT NULL,
DEPT_CODE VARCHAR(10) UNIQUE NOT NULL

);
CREATE TABLE BATCHES(
BATCH_ID INT PRIMARY KEY AUTO_INCREMENT,
START_YEAR INT NOT NULL ,
END_YEAR INT NOT NULL,
BATCH_NAME VARCHAR(20) GENERATED ALWAYS AS (CONCAT(START_YEAR,'-',END_YEAR)) STORED ,CHECK (END_YEAR >START_YEAR)
); 
CREATE TABLE STUDENTDETAILS(
ID INT PRIMARY KEY auto_increment,
FIRST_NAME VARCHAR(100) NOT NULL,
LAST_NAME VARCHAR(100) NOT NULL,
GENDER ENUM('FEMALE','MALE','OTHER'),
DOB DATE not null,
SEMESTER INT not null ,CHECK(SEMESTER <=8 AND SEMESTER >=1) ,
DEPT_ID INT,
BATCH_ID INT,
EMAIL VARCHAR(200) NOT NULL unique,
PHONE_NUM VARCHAR(15) NOT NULL unique,
FOREIGN KEY(BATCH_ID) REFERENCES BATCHES(BATCH_ID)
   on DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(DEPT_ID) REFERENCES DEPARTMENT(DEPT_ID)
  on DELETE CASCADE ON UPDATE CASCADE
);


select * from studentdetails;
ALTER TABLE STUDENTDETAILS
ADD CURRENT_GPA DECIMAL(3,2) NULL;
CREATE TABLE SEMESTER(
SEMESTER_ID INT PRIMARY KEY auto_increment,
SEMESTER_NUM INT NOT NULL unique 
);
CREATE TABLE FACULTY_DEATILS(
FACULTY_ID INT PRIMARY KEY auto_increment NOT NULL UNIQUE,
FACULTY_NAME VARCHAR(100) NOT NULL,
FACULTY_CODE VARCHAR(20) UNIQUE NOT NULL,
EMAIL VARCHAR(200) UNIQUE NOT NULL,
PHONE_NUMBER VARCHAR(20) UNIQUE NOT NULL ,CHECK(PHONE_NUMBER REGEXP '^[+]?[0-9]{10,15}$')
);
rename table FACULTY_DEATILS to FACULTY_DETAILS;
CREATE TABLE COURSE(
COURSE_ID INT PRIMARY KEY auto_increment,
COURSE_NAME VARCHAR(100)  NOT NULL,
DEPT_ID INT,
foreign key (DEPT_ID) references DEPARTMENT(DEPT_ID)
  on DELETE CASCADE ON UPDATE CASCADE,
COURSE_CODE VARCHAR(20) UNIQUE NOT NULL
);
alter table course
add credits int not null;
select * from course;

CREATE TABLE COURSE_OFFERING(
COURSE_OFFERING_ID INT PRIMARY KEY auto_increment,
COURSE_ID INT,
SEMESTER_ID INT NOT NULL,
FACULTY_ID INT NOT NULL,
ACADEMIC_YEAR INT NOT NULL,
CAPACITY INT,
foreign key (FACULTY_ID) references FACULTY_DETAILS(FACULTY_ID)
  on DELETE CASCADE ON UPDATE CASCADE,
foreign key (SEMESTER_ID) references SEMESTER(SEMESTER_ID)
   on DELETE CASCADE ON UPDATE CASCADE,
foreign key (COURSE_ID) references COURSE(COURSE_ID)
  on DELETE CASCADE ON UPDATE CASCADE
);

SELECT * FROM COURSE_OFFERING;


ALTER TABLE COURSE_OFFERING
ADD DEPT_ID INT NOT NULL,
ADD CONSTRAINT fk_course_offering_dept
FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT(DEPT_ID)
  on DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE ATTENDANCE(
STUDENT_ID INT NOT NULL,
COURSE_OFFERING_ID INT NOT NULL,
ATTENDANCE_DATE DATE NOT NULL,
STATUS ENUM('PRESSENT','ABSENT') NOT NULL,
foreign key (student_id) references studentdetails(id)
  on DELETE CASCADE ON UPDATE CASCADE,
foreign key (COURSE_OFFERING_ID) references course_offering(course_offering_id)
  on DELETE CASCADE ON UPDATE CASCADE,
UNIQUE (STUDENT_ID, COURSE_OFFERING_ID, ATTENDANCE_DATE)  -- prevents duplicate marking
);
ALTER TABLE ATTENDANCE 
CHANGE STATUS STATUS ENUM('PRESENT','ABSENT') NOT NULL;
create table ENROLLMENTS (
ENROLLMENT_ID INT PRIMARY KEY auto_increment, -- REQUIRED FOR ACCESING STUDENT AND COURSE ENROLLED IN GRADE TABLE
ID INT ,
COURSE_OFFERING_ID INT NOT NULL,
foreign key (ID) references studentdetails(id)
  on DELETE CASCADE ON UPDATE CASCADE,
foreign key (COURSE_OFFERING_ID) references COURSE_OFFERING(COURSE_OFFERING_ID)
  on DELETE CASCADE ON UPDATE CASCADE,
UNIQUE(ID, COURSE_OFFERING_ID)

);

CREATE TABLE GRADE(
GRADE_ID INT PRIMARY KEY auto_increment,
ENROLLMENT_ID INT , -- STORES THE GRADES FOR PERTICULAR STUDENT IN SPECIFIC COURSE 
foreign key (ENROLLMENT_ID) REFERENCES ENROLLMENTS(ENROLLMENT_ID)
 on DELETE CASCADE ON UPDATE CASCADE,
GRADE ENUM('A','B','C','D'),
GRADE_POINT DECIMAL(3,2) AS(-- DECIMAL(N,D)-->N-TOTAL NUMBER OF DEGITS IN TOTAL ,D-->TOTAL NUMBER OF DIGITS AFTER DECIMAL
     CASE 
         WHEN GRADE ='A' THEN 4.00
         WHEN GRADE ='B' THEN 3.00
         WHEN GRADE ='C' THEN 2.00
         WHEN GRADE ='D' THEN 1.00
         ELSE 0.0
     END
)STORED
);
CREATE VIEW STUDENT_GPA AS
SELECT S.ID,CONCAT(S.FIRST_NAME ,' ',S.LAST_NAME) AS STUDENT_NAME,ROUND(SUM(G.GRADE_POINT)/COUNT(*),2) AS GPA
FROM ENROLLMENTS E
JOIN GRADE G ON E.ENROLLMENT_ID=G.ENROLLMENT_ID
JOIN STUDENTDETAILS S ON E.ID=S.ID
GROUP BY S.ID;


CREATE TABLE TRIGGER_LOG(
LOG_ID INT AUTO_INCREMENT PRIMARY KEY,
EVENT_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ACTION_TYPE VARCHAR(20),
ENROLLMENT_ID INT,
STUD_ID INT,
MESSAGE TEXT
);
DELIMITER $$

CREATE PROCEDURE UPDATE_GPA(IN P_ACTION_TYPE VARCHAR(20),IN ENROLLMENT_ID_P INT)
BEGIN
    DECLARE new_gpa DECIMAL(5,2);
    DECLARE stud_id INT;

    DECLARE CONTINUE HANDLER FOR NOT FOUND SET stud_id=NULL;
    SELECT ID INTO stud_id
    FROM ENROLLMENTS
    WHERE ENROLLMENT_ID = ENROLLMENT_ID_P;

  IF stud_id IS NOT NULL THEN
    SELECT ROUND(SUM(g.GRADE_POINT)/COUNT(*),2)
    INTO new_gpa
    FROM GRADE g
    JOIN ENROLLMENTS e ON g.ENROLLMENT_ID = e.ENROLLMENT_ID
    WHERE e.ID = stud_id;
    
    IF new_gpa IS NULL THEN
            SET new_gpa = 0.00;
        END IF;
   
    UPDATE STUDENTDETAILS
    SET CURRENT_GPA = new_gpa
    WHERE ID = stud_id;
   ELSE 
      INSERT INTO TRIGGER_LOG(ACTION_TYPE,ENROLLMENT_ID,STUD_ID,MESSAGE)
      VALUES (P_ACTION_TYPE,  ENROLLMENT_ID_P, NULL, 'No student found for this enrollment_id');
  END IF;  
END$$

DELIMITER ;
   
DELIMITER $$

CREATE TRIGGER trg_update_after_insert
AFTER INSERT ON grade
FOR EACH ROW
BEGIN
    CALL UPDATE_GPA('INSERT',NEW.ENROLLMENT_ID);
END$$

DELIMITER ;


DELIMITER $$

CREATE TRIGGER trg_update_gpa_after_update
AFTER UPDATE ON GRADE
FOR EACH ROW
BEGIN
   CALL UPDATE_GPA('UPDATE',NEW.ENROLLMENT_ID);
END$$

DELIMITER ;

DELIMITER $$

CREATE TRIGGER trg_update_gpa_after_delete
AFTER DELETE ON GRADE
FOR EACH ROW
BEGIN
   CALL UPDATE_GPA('DELETE',OLD.ENROLLMENT_ID);
END$$

DELIMITER ;
/*
-- Step 1: Disable foreign key checks
 SET FOREIGN_KEY_CHECKS = 0;

-- Step 2: Drop tables in reverse dependency order
DROP VIEW IF EXISTS STUDENT_GPA;
 DROP TABLE IF EXISTS grade;
DROP TABLE IF EXISTS enrollments;
DROP TABLE IF EXISTS attendance;
DROP TABLE IF EXISTS course_offering;
DROP TABLE IF EXISTS course;
DROP TABLE IF EXISTS faculty_details;
DROP TABLE IF EXISTS semester;
DROP TABLE IF EXISTS studentdetails;
DROP TABLE IF EXISTS batches;
DROP TABLE IF EXISTS department;

-- Step 3: Enable foreign key checks back
SET FOREIGN_KEY_CHECKS = 1;

-- ✅ Now all tables are dropped, start fresh

drop table if exists trigger_log ;

drop procedure if exists update_gpa;
*/
ALTER TABLE COURSE AUTO_INCREMENT = 1;
ALTER TABLE COURSE_OFFERING AUTO_INCREMENT = 1;
ALTER TABLE STUDENTDETAILS AUTO_INCREMENT = 1;
ALTER TABLE ENROLLMENTS AUTO_INCREMENT = 1;
ALTER TABLE GRADE AUTO_INCREMENT = 1;
ALTER TABLE ATTENDANCE AUTO_INCREMENT = 1;
ALTER TABLE DEPARTMENT AUTO_INCREMENT = 1;
ALTER TABLE BATCHES AUTO_INCREMENT = 1;
ALTER TABLE SEMESTER AUTO_INCREMENT = 1;
ALTER TABLE FACULTY_DETAILS AUTO_INCREMENT = 1;


